services:
  csgowatchdog:
    image: csgowatchdog
    container_name: csgowatchdog
    restart: unless-stopped
    user: 1000:1000
    tty: true
    stdin_open: true
    volumes:
      - ./watchdog:/watchdog
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    network_mode: bridge
    env_file:
      - example.global.env
  csgo-server-1:
    image: csgoserver
    container_name: csgo-server-1
    restart: unless-stopped
    user: 1000:1000
    tty: true
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-file: 5
        max-size: 10m
    network_mode: host
    env_file:
      - example.global.env
      - exaple1.env
    volumes:
      - ./watchdog:/watchdog
      - ./layers:/layers:ro
      - ./mounts:/mounts
      - ./user:/user:ro
