FROM debian:bookworm-slim

RUN dpkg --add-architecture i386 \
    && apt-get update -y \
    && apt-get install -y --no-install-recommends --no-install-suggests \
        lib32stdc++6 ca-certificates curl jq tar unzip zip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY csgowatchdog.sh .
RUN chmod 555 csgowatchdog.sh

ENTRYPOINT ["/app/csgowatchdog.sh"]
